AWSTemplateFormatVersion: '2010-09-09'
Description: F11 AWS Lambda function to send tokens
Resources:
  LambdaFunction:
    Properties:
      FunctionName: f11 
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          PRIVATEKEY: "get_one_with_the_f11_"
          PUBLICKEY: "gaiacli_keys_can_give_this_to_you"
          ACCOUNTADDRESS: "gaiacli_keys_can_give_this_to_you"
          NODE: "http://127.0.0.1:26657"
          LCDNODEURL: "http://127.0.0.1:1317"
          AMOUNT: "10steak"
          ORIGINS: "http://localhost"
          REDISENDPOINT: "get_one_from_redislabs"
          REDISPASSWORD: "get_one_from_redislabs"
          RECAPTCHASECRET: "get_one_from_Google"
          TIMEOUT: "60"
          AWSREGION: "us-east-1"
      Events:
        RootHandler:
          Type: Api
          Properties:
            Path: '/'
            Method: get
        ClaimHandler:
          Type: Api
          Properties:
            Path: '/v1/claim'
            Method: POST
        ClaimHandlerOptions:
          Type: Api
          Properties:
            Path: "/v1/claim"
            Method: OPTIONS
      Handler: build/f11
      Runtime: go1.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31

